"""Fix about_me problem

Revision ID: 464646c3a214
Revises: 479bd793edb8
Create Date: 2020-11-07 12:58:31.921684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464646c3a214'
down_revision = '479bd793edb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
