"""remove about_me column

Revision ID: 479bd793edb8
Revises: 82f25f0f2776
Create Date: 2020-11-07 12:44:40.504642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479bd793edb8'
down_revision = '82f25f0f2776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('user', 'anout_me')
    # op.drop_column('user', 'about_me')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('about_me')
        batch_op.drop_column('anout_me')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('anout_me', sa.VARCHAR(length=140), nullable=True))
    op.add_column('user', sa.Column('about_me', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
