"""empty message

Revision ID: 82f25f0f2776
Revises: dc47302ed028
Create Date: 2020-11-07 11:07:38.703505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f25f0f2776'
down_revision = 'dc47302ed028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('anout_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_been', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_been')
    op.drop_column('user', 'anout_me')
    # ### end Alembic commands ###
